name: Benchmark

on:
  workflow_dispatch: {}
  schedule:
    # https://crontab.guru/#*/5_*/12_*_*_*
    - cron: "*/5 */12 * * *" 



jobs:
  build:
    runs-on: ${{ matrix:runner }}
    strategy:
      matrix:
        runner:
        - devzero-ubuntu-24.04
        - devzero-ubuntu-24.04-lab
        - devzero-ubuntu-24.04-lab-kata-overlayfs
        - devzero-ubuntu-24.04-sysbox
    steps:
      - name: ${{ matrix:runner }}
        run: |
          git clone https://github.com/moby/buildkit --depth=1
          cd buildkit
          make binaries
