name: Benchmark

on:
  workflow_dispatch: {}
  schedule:
    # https://crontab.guru/#1_*/11_*_*_*
    - cron: "1 */11 * * *" 
    

jobs:
  build-with-github-hosted-runner:
    name: Build with GitHub hosted runners
    runs-on: ubuntu-22.04
    steps:
      - name: Clone buildkit and make binaries
        run: |
          git clone https://github.com/moby/buildkit --depth=1
          cd buildkit
          make binaries

  build-with-devzero-hosted-runner:
    name: Build with DevZero hosted runners
    runs-on: devzero-ubuntu-24.04
    steps:
      - name: Clone buildkit and make binaries
        run: |
          git clone https://github.com/moby/buildkit --depth=1
          cd buildkit
          make binaries
