name: Benchmark

on:
  workflow_dispatch: {}
    

jobs:
  build-with-github-hosted-runner:
    name: Build with GitHub hosted runners
    runs-on: ubuntu-22.04
    steps:
      - name: Clone buildkit and make binaries
        run: |
          git clone https://github.com/moby/buildkit --depth=1
          cd buildkit
          make binaries

  build-with-devzero-hosted-runner:
    name: Build with DevZero hosted runners
    runs-on: devzero-ubuntu-24.04
    steps:
      - name: Clone buildkit and make binaries
        run: |
          git clone https://github.com/moby/buildkit --depth=1
          cd buildkit
          make binaries
          
  build-with-bare-metal:
    name: Build with DevZero bare-metal runners
    runs-on: devzero-ubuntu-24.04-bare-metal
    steps:
      - name: Clone buildkit and make binaries
        run: |
          rm -rf buildkit  # Remove existing directory if it exists
          git clone https://github.com/moby/buildkit --depth=1
          cd buildkit
          make binaries
